...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -8,28 +8,49 @@ alias giss="git status -s"
 alias gib="git branch"
 
 gia(){
-    if [ "$1" == "" ]; then
+    if [ "$1" = "" ]; then
         git add .;
     else
         git add "$@";
     fi
 }
 
+gisy(){
+    giam "$@"
+    git status -s
+    printf "Enter to continue. Other to abort." >&2
+    local key
+    read -r key
+    if [ "$key" != "" ]; then
+        printf "%s" "Abort. Because read $key" >&2
+        return 1
+    fi
+
+    x push || {
+        giP
+    }
+}
+
 giam(){
-    local first_arg="$2"
-    git add "${2:-.}" "${@:3:}"
-    git commit -m "$1"
+    local msg="${1:-Provide message}"
+    shift
+    if [ $# -eq 0 ]; then
+        git add .
+    else
+        git add "$@"
+    fi
+    git commit -m "$msg"
 }
 
 gip(){
-    git pull origin $(git branch | awk '$1=="*"{ print $2 }' )
+    git pull origin "$(git rev-parse --abbrev-ref HEAD)"
 }
 
 giP(){
     if [ -e "$1" ]; then
         git push origin $1
     else
-        git push origin $(git branch | awk '$1=="*"{ print $2 }')
+        git push origin "$(git rev-parse --abbrev-ref HEAD)"
     fi
 }
 
